/**
 * Contract PDF Generator — V1 Stub
 *
 * Generates an HTML document from a contract template + variables,
 * uploads it to Supabase Storage, and returns the public URL.
 *
 * NOTE: In production, swap the HTML generation for a proper PDF library:
 *   - pdf-lib (pure JS, no headless browser needed)
 *   - puppeteer (headless Chrome, high fidelity)
 *   - WeasyPrint (server-side Python, excellent CSS support)
 *
 * Template variable syntax: {{variable_name}}
 * Supported variables:
 *   {{nurse_name}}, {{facility_name}}, {{shift_date}}, {{rate}},
 *   {{hours}}, {{role}}, {{start_date}}, {{end_date}},
 *   {{platform_fee}}, {{total_compensation}}
 */

import { createClient } from '@supabase/supabase-js'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ContractVariables {
  nurse_name?: string
  facility_name?: string
  shift_date?: string
  rate?: string | number
  hours?: string | number
  role?: string
  start_date?: string
  end_date?: string
  platform_fee?: string | number
  total_compensation?: string | number
  [key: string]: string | number | undefined
}

export interface GeneratePdfOptions {
  contractId: string
  templateId?: string
  variables?: ContractVariables
  /** Pre-rendered HTML content (skips template fetch if provided) */
  htmlContent?: string
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getServiceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !serviceKey) {
    throw new Error('Supabase env vars missing for PDF generator.')
  }
  return createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
}

/**
 * Replace {{variable}} placeholders in a template string.
 */
function interpolate(template: string, variables: ContractVariables): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => {
    const val = variables[key]
    return val !== undefined ? String(val) : `{{${key}}}`
  })
}

/**
 * Wrap contract content in a styled HTML document.
 */
function wrapHtml(content: string, title: string): string {
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Georgia', serif;
      font-size: 14px;
      line-height: 1.7;
      color: #1a1a2e;
      background: #ffffff;
      padding: 60px 80px;
      max-width: 900px;
      margin: 0 auto;
    }
    .header {
      border-bottom: 3px solid #6366f1;
      padding-bottom: 20px;
      margin-bottom: 32px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .header h1 { font-size: 24px; color: #6366f1; font-weight: bold; }
    .header .meta { font-size: 12px; color: #666; text-align: right; }
    .section { margin-bottom: 28px; }
    .section h2 { font-size: 16px; font-weight: bold; margin-bottom: 10px; color: #4338ca; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    p { margin-bottom: 12px; }
    .signature-block {
      margin-top: 60px;
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 60px;
    }
    .sig-line { border-top: 1px solid #333; padding-top: 8px; margin-top: 48px; font-size: 12px; color: #555; }
    .footer { margin-top: 60px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
    .badge { display: inline-block; background: #ede9fe; color: #6366f1; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-family: monospace; }
  </style>
</head>
<body>
  <div class="header">
    <h1>NurseSphere Contract</h1>
    <div class="meta">
      <div>${title}</div>
      <div>Generated: ${now}</div>
      <div class="badge">STUB DOCUMENT</div>
    </div>
  </div>

  <div class="content">
    ${content}
  </div>

  <div class="signature-block">
    <div>
      <div class="sig-line">Nurse Signature &amp; Date</div>
    </div>
    <div>
      <div class="sig-line">Facility Administrator Signature &amp; Date</div>
    </div>
  </div>

  <div class="footer">
    This document was generated by NurseSphere. It is legally binding upon execution by all parties.
    &copy; ${new Date().getFullYear()} NurseSphere Inc. All rights reserved.
  </div>
</body>
</html>`
}

/**
 * Default contract template used when no templateId is specified.
 */
function buildDefaultTemplate(variables: ContractVariables): string {
  return `
<div class="section">
  <h2>1. Parties</h2>
  <p>This Employment Agreement ("Agreement") is entered into between <strong>{{facility_name}}</strong>
  ("Facility") and <strong>{{nurse_name}}</strong> ("Healthcare Professional") effective as of
  <strong>{{start_date}}</strong>.</p>
</div>

<div class="section">
  <h2>2. Position &amp; Assignment</h2>
  <p>The Healthcare Professional is engaged as a <strong>{{role}}</strong>. The assignment
  covers the period from <strong>{{start_date}}</strong> to <strong>{{end_date}}</strong>.</p>
  <p>Scheduled shift date: <strong>{{shift_date}}</strong>, for <strong>{{hours}} hours</strong>.</p>
</div>

<div class="section">
  <h2>3. Compensation</h2>
  <p>The Healthcare Professional shall receive an hourly rate of <strong>{{rate}}/hr</strong>.</p>
  <p>Platform fee: <strong>{{platform_fee}}</strong></p>
  <p>Total estimated compensation: <strong>{{total_compensation}}</strong></p>
</div>

<div class="section">
  <h2>4. Scope of Work</h2>
  <p>The Healthcare Professional agrees to provide clinical staffing services as directed by the
  Facility's charge nurse or department supervisor. All patient care activities must comply with
  applicable state and federal regulations, facility policies, and professional licensing standards.</p>
</div>

<div class="section">
  <h2>5. Confidentiality &amp; HIPAA</h2>
  <p>The Healthcare Professional agrees to maintain the confidentiality of all patient information
  in compliance with HIPAA (45 CFR Parts 160 and 164) and any applicable state laws.</p>
</div>

<div class="section">
  <h2>6. Independent Contractor Status</h2>
  <p>The Healthcare Professional is engaged as an independent contractor. Nothing in this Agreement
  creates an employer-employee relationship. The Healthcare Professional is solely responsible for
  their own taxes, insurance, and professional licensing.</p>
</div>

<div class="section">
  <h2>7. Termination</h2>
  <p>Either party may terminate this agreement with 24 hours' written notice. Immediate termination
  is permitted in cases of patient safety violations, professional misconduct, or material breach
  of this Agreement.</p>
</div>

<div class="section">
  <h2>8. Governing Law</h2>
  <p>This Agreement shall be governed by the laws of the state in which the Facility is located.
  Any disputes shall be resolved through binding arbitration.</p>
</div>
  `.replace(/\{\{(\w+)\}\}/g, (_, key: string) => {
    const val = variables[key as keyof ContractVariables]
    return val !== undefined ? String(val) : `[${key.toUpperCase()}]`
  })
}

// ─── Main Export ──────────────────────────────────────────────────────────────

/**
 * Generate an HTML contract document and upload to Supabase Storage.
 * Returns the public URL of the uploaded document.
 *
 * @param contractId  - UUID of the contract record
 * @param templateId  - Optional UUID of a contract_templates record
 * @param variables   - Variable substitutions for the template
 * @returns Public URL of the uploaded HTML document
 */
export async function generateContractPdf(
  contractId: string,
  templateId?: string | null,
  variables: ContractVariables = {}
): Promise<string> {
  const supabase = getServiceClient()

  let htmlBody: string
  let documentTitle = `Contract ${contractId.slice(0, 8).toUpperCase()}`

  if (templateId) {
    // Fetch template from DB
    const { data: template, error } = await supabase
      .from('contract_templates')
      .select('name, content')
      .eq('id', templateId)
      .single()

    if (error || !template) {
      throw new Error(`Template not found: ${templateId}`)
    }

    documentTitle = template.name
    htmlBody = interpolate(template.content, variables)
  } else {
    // Use built-in default template
    htmlBody = buildDefaultTemplate(variables)
  }

  const fullHtml = wrapHtml(htmlBody, documentTitle)
  const fileName = `contracts/${contractId}/document_${Date.now()}.html`

  // Ensure the storage bucket exists (phantom guard)
  const bucketName = process.env.SUPABASE_CONTRACTS_BUCKET ?? 'contracts'

  const { error: uploadError } = await supabase.storage
    .from(bucketName)
    .upload(fileName, Buffer.from(fullHtml, 'utf-8'), {
      contentType: 'text/html',
      upsert: true,
    })

  if (uploadError) {
    // Fallback: store HTML as base64 data URL if storage fails
    console.warn('[PDFGenerator] Storage upload failed, using data URL fallback:', uploadError.message)
    const base64 = Buffer.from(fullHtml, 'utf-8').toString('base64')
    return `data:text/html;base64,${base64}`
  }

  // Get public URL
  const { data: urlData } = supabase.storage
    .from(bucketName)
    .getPublicUrl(fileName)

  return urlData.publicUrl
}
